DROP TABLE IF EXISTS ChallengeParticipant;
DROP TABLE IF EXISTS ActiveChallenge;
DROP TABLE IF EXISTS Participant;
DROP TABLE IF EXISTS UserCreatedChallenge;


CREATE TABLE Participant (
    user_id BIGINT NOT NULL PRIMARY KEY,
    username VARCHAR(45) NOT NULL,
    joined DATE NOT NULL,
    reputation INTEGER CHECK (reputation >= 0) NOT NULL,
    completed_challenge INTEGER CHECK(completed_challenge >= 0) NOT NULL
);

CREATE TABLE UserCreatedChallenge(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    max_participants INTEGER DEFAULT 7
);

CREATE TABLE ActiveChallenge (
    active_challenge_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES Participant(user_id),
    challenge_id INTEGER references UserCreatedChallenge(id),
    creation_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    is_finished BOOLEAN NOT NULL
);

CREATE TABLE ChallengeParticipant (
    user_id BIGINT REFERENCES Participant(user_id),
    challenge_id INTEGER REFERENCES ActiveChallenge(active_challenge_id),
    is_kicked BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id, challenge_id)
);

INSERT INTO UserCreatedChallenge (owner_id, title, description, creation_date) VALUES (0, 'Потребление овощей и фруктов', 'Челлендж включает в себя потребление различных овощей и фруктов каждый день в размере не менее 500 г.', current_timestamp);
INSERT INTO UserCreatedChallenge (owner_id, title, description, creation_date) VALUES (0, 'Здоровый сон', 'Челлендж включает в себя полноценный сон в установленное количество часов', current_timestamp);
INSERT INTO UserCreatedChallenge (owner_id, title, description, creation_date) VALUES (0, 'Гидратация', 'Челлендж включает в себя потребление не менее 2 литров чистой воды в день.', current_timestamp);
INSERT INTO UserCreatedChallenge (owner_id, title, description, creation_date) VALUES (0, '10 000 шагов', 'Челлендж включает в себя ежедневное преодоление дистанции в 10 000 шагов.', current_timestamp);
INSERT INTO UserCreatedChallenge (owner_id, title, description, creation_date) VALUES (0, 'Медитация', 'Челлендж включает в себя ежедневную практику медитации на протяжении не менее 15 минут.', current_timestamp);
INSERT INTO UserCreatedChallenge (owner_id, title, description, creation_date) VALUES (0, 'Без сахара', 'Челлендж включает в себя исключение из рациона продуктов, содержащих добавленный сахар.', current_timestamp);
