DROP TABLE IF EXISTS ChallengeParticipant;
DROP TABLE IF EXISTS ActiveChallenge;
DROP TABLE IF EXISTS Participant;
DROP TABLE IF EXISTS Challenge;


CREATE TABLE Participant (
    user_id BIGINT NOT NULL PRIMARY KEY,
    username VARCHAR(45) NOT NULL,
    joined DATE NOT NULL,
    reputation INTEGER CHECK (reputation >= 0) NOT NULL,
    completed_challenge INTEGER CHECK(completed_challenge >= 0) NOT NULL
);

CREATE TABLE Challenge (
    challenge_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_title TEXT NOT NULL,
    challenge_description TEXT
);

CREATE TABLE ActiveChallenge (
    active_challenge_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES Participant(user_id),
    challenge_id INTEGER references Challenge(challenge_id),
    creation_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    is_finished BOOLEAN NOT NULL
);

CREATE TABLE ChallengeParticipant (
    participant_id BIGINT REFERENCES Participant(user_id),
    challenge_id INTEGER REFERENCES Challenge(challenge_id),
    is_kicked BOOLEAN NOT NULL,
    PRIMARY KEY (participant_id, challenge_id)
);

INSERT INTO Challenge (challenge_title, challenge_description) VALUES ('Потребление овощей и фруктов', 'Челлендж включает в себя потребление различных овощей и фруктов каждый день в размере не менее 500 г.');
INSERT INTO Challenge (challenge_title, challenge_description) VALUES ('Здоровый сон', 'Челлендж включает в себя полноценный сон в установленное количество часов');
INSERT INTO Challenge (challenge_title, challenge_description) VALUES ('Гидратация', 'Челлендж включает в себя потребление не менее 2 литров чистой воды в день.');
INSERT INTO Challenge (challenge_title, challenge_description) VALUES ('10 000 шагов', 'Челлендж включает в себя ежедневное преодоление дистанции в 10 000 шагов.');
INSERT INTO Challenge (challenge_title, challenge_description) VALUES ('Медитация', 'Челлендж включает в себя ежедневную практику медитации на протяжении не менее 15 минут.');
INSERT INTO Challenge (challenge_title, challenge_description) VALUES ('Без сахара', 'Челлендж включает в себя исключение из рациона продуктов, содержащих добавленный сахар.');
